package frontend.utils;

import java.util.Arrays;
import java.util.HashSet;

public class Template {
    public static final HashSet<String> fkWords= new HashSet<String>(Arrays.asList("15619cctest","4r5e","5h1t","5hit","n1gga","n1gger",
            "nobhead","nobjocky","nobjokey","nutsack","numbnuts","nazi","nigg3r","nigg4h","nigga","niggas","niggaz",
            "niggah","nigger","niggers","omg","p0rn","poop","pron","prick","pricks","pussy","pussys","pusse","pussi",
            "pussies","pube","pawn","penis","penisfucker","phonesex","phuq","phuck","phuk","phuks","phuked","phuking",
            "phukked","phukking","piss","pissoff","pisser","pissers","pisses","pissflaps","pissin","pissing",
            "pigfucker","pimpis","queer","rectum","rimjaw","rimming","snatch","sonofabitch","spunk","scrotum",
            "scrote","scroat","schlong","sex","semen","sh1t","shit","shits","shitty","shitter","shitters","shitted",
            "shitting","shittings","shitdick","shite","shitey","shited","shitfuck","shitfull","shithead","shiting",
            "shitings","skank","slut","smut","smegma","tosser","turd","tw4t","twunt","twunter","twat","twatty",
            "twathead","teets","tit","tittywank","tittyfuck","titties","tittiefucker","titwank","titfuck","v14gra",
            "v1gra","vulva","vagina","viagra","w00se","wtff","wang","wank","wanky","wanker","whore","whore4r5e",
            "whoreshit","whoreanal","whoar","a55","anus","anal","arse","ass","assram","asswhole","assfucker",
            "assfukka","assho","b00bs","b17ch","b1tch","boner","booooooobs","booooobs","boooobs","booobs","boob",
            "boobs","boiolas","bollock","bollok","breasts","bunnyfucker","butt","buttplug","buttmuch","buceta",
            "bugger","bullshit","bum","bastard","balls","ballsack","bestial","bestiality","beastial","beastiality",
            "bellend","bitch","biatch","bloody","blowjob","blowjobs","c0ck","c0cksucker","cnut","coon","cox","cock",
            "cocks","cocksuck","cocksucks","cocksucker","cocksucked","cocksucking","cocksuka","cocksukka","cockface",
            "cockhead","cockmunch","cockmuncher","cok","coksucka","cokmuncher","crap","cunnilingus","cunt","cunts",
            "cuntlick","cuntlicker","cuntlicking","cunilingus","cunillingus","cum","cums","cumshot","cummer","cumming",
            "cyalis","cyberfuc","cyberfuck","cyberfucker","cyberfuckers","cyberfucked","cyberfucking","carpetmuncher",
            "cawk","chink","cipa","cl1t","clit","clitoris","clits","d1ck","donkeyribber","doosh","dogfucker","doggin",
            "dogging","duche","dyke","damn","dink","dinks","dirsa","dick","dickhead","dildo","dildos","dlck",
            "ejaculate","ejaculates","ejaculated","ejaculating","ejaculatings","ejaculation","ejakulate","f4nny",
            "fook","fooker","fux","fux0r","fuck","fucks","fuckwhit","fuckwit","fucka","fucker","fuckers","fucked",
            "fuckhead","fuckheads","fuckin","fucking","fuckings","fuckingshitmotherfucker","fuckkkdatttbitchhhh",
            "fuckme","fudgepacker","fuk","fuks","fukwhit","fukwit","fuker","fukker","fukkin","fannyfucker",
            "fannyflaps","fanyy","fag","fagot","fagots","fags","faggot","faggs","fagging","faggitt","fcuk","fcuker",
            "fcuking","feck","fecker","felching","fellate","fellatio","fingerfuck","fingerfucks","fingerfucker",
            "fingerfuckers","fingerfucked","fingerfucking","fistfuck","fistfucks","fistfucker","fistfuckers",
            "fistfucked","fistfucking","fistfuckings","flange","goatse","goddamn","gangbang","gangbangs","gangbanged",
            "gaysex","horny","horniest","hore","hotsex","hoar","hoare","hoer","homo","hardcoresex","heshe","hell",
            "jap","jackoff","jerk","jerkoff","jism","jiz","jizz","jizm","knob","knobend","knobead","knobed","knobhead",
            "knobjocky","knobjokey","kondum","kondums","kock","kunilingus","kum","kums","kummer","kumming","kawk",
            "l3itch","l3ich","lust","lusting","labia","lmao","lmfao","m0f0","m0fo","m45terbate","mothafuck",
            "mothafucks","mothafucka","mothafuckas","mothafuckaz","mothafucker","mothafuckers","mothafucked",
            "mothafuckin","mothafucking","mothafuckings","motherfuck","motherfucks","motherfucker","motherfuckers",
            "motherfucked","motherfuckin","motherfucking","motherfuckings","motherfuckka","mof0","mofo","mutha",
            "muthafuckker","muthafecker","muther","mutherfucker","muff","ma5terb8","ma5terbate","masochist",
            "masturbate","masterb8","masterbat","masterbat3","masterbate","masterbation","masterbations"));
    public boolean[][] ver1Template = {
            //0   ,1    ,2    ,3    ,4    ,5    ,6    ,7    ,8    ,9    ,10   ,11   ,12   ,13   ,14   ,15   ,16   ,17   ,18   ,19   ,20
/*0*/{ true, true, true, true, true, true, true, false, false, false, false, false, false, false, true, true, true,
            true, true, true, true },
/*1*/{ true, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false,
            false, false, false, false, true },
/*2*/{ true, false, true, true, true, false, true, false, false, false, false, false, false, false, true, false, true,
            true, true, false, true },
/*3*/{ true, false, true, true, true, false, true, false, false, false, false, false, false, false, true, false, true,
            true, true, false, true },
/*4*/{ true, false, true, true, true, false, true, false, false, false, false, false, false, false, true, false, true,
            true, true, false, true },
/*5*/{ true, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false,
            false, false, false, false, true },
/*6*/{ true, true, true, true, true, true, true, false, true, false, true, false, true, false, true, true, true, true,
            true, true, true },
/*7*/{ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*8*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*9*/{ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*10*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*11*/{ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*12*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*13*/{ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*14*/{ true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false,
            false, false, false, false },
/*15*/{ true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*16*/{ true, false, true, true, true, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*17*/{ true, false, true, true, true, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*18*/{ true, false, true, true, true, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*19*/{ true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*20*/{ true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false,
            false, false, false, false }, };
    public boolean[][] ver1Occupied = {
            //0   ,1    ,2    ,3    ,4    ,5    ,6    ,7    ,8    ,9    ,10   ,11   ,12   ,13   ,14   ,15   ,16   ,17   ,18   ,19   ,20
/*0*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, true, true,
            true, true, true },
/*1*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, true, true,
            true, true, true },
/*2*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, true, true,
            true, true, true },
/*3*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, true, true,
            true, true, true },
/*4*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, true, true,
            true, true, true },
/*5*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, true, true,
            true, true, true },
/*6*/{ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
            true, true },
/*7*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, true, true,
            true, true, true },
/*8*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*9*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*10*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*11*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*12*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false },
/*13*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false },
/*14*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false },
/*15*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false },
/*16*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false },
/*17*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false },
/*18*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false },
/*19*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false },
/*20*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false }, };
    public boolean[][] ver2Template = {
            //0   ,1    ,2    ,3    ,4    ,5    ,6    ,7    ,8    ,9    ,10   ,11   ,12   ,13   ,14   ,15   ,16   ,17   ,18   ,19   ,20   ,21   ,22   ,23   ,24
/*0*/{ true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false,
            false, true, true, true, true, true, true, true },
/*1*/{ true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, true, false, false, false, false, false, true },
/*2*/{ true, false, true, true, true, false, true, false, false, false, false, false, false, false, false, false, false,
            false, true, false, true, true, true, false, true },
/*3*/{ true, false, true, true, true, false, true, false, false, false, false, false, false, false, false, false, false,
            false, true, false, true, true, true, false, true },
/*4*/{ true, false, true, true, true, false, true, false, false, false, false, false, false, false, false, false, false,
            false, true, false, true, true, true, false, true },
/*5*/{ true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, true, false, false, false, false, false, true },
/*6*/{ true, true, true, true, true, true, true, false, true, false, true, false, true, false, true, false, true, false,
            true, true, true, true, true, true, true },
/*7*/{ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*8*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*9*/{ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*10*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*11*/{ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*12*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*13*/{ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*14*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*15*/{ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*16*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            true, true, true, true, true, false, false, false, false },
/*17*/{ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
            true, false, false, false, true, false, false, false, false },
/*18*/{ true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, true,
            false, true, false, true, false, false, false, false },
/*19*/{ true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            true, false, false, false, true, false, false, false, false },
/*20*/{ true, false, true, true, true, false, true, false, false, false, false, false, false, false, false, false, true,
            true, true, true, true, false, false, false, false },
/*21*/{ true, false, true, true, true, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*22*/{ true, false, true, true, true, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*23*/{ true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*24*/{ true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false }, };
    public boolean[][] ver2Occupied = {
            //0   ,1    ,2    ,3    ,4    ,5    ,6    ,7    ,8    ,9    ,10   ,11   ,12   ,13   ,14   ,15   ,16   ,17   ,18   ,19   ,20   ,21   ,22   ,23   ,24
/*0*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            true, true, true, true, true, true, true, true },
/*1*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            true, true, true, true, true, true, true, true },
/*2*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            true, true, true, true, true, true, true, true },
/*3*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            true, true, true, true, true, true, true, true },
/*4*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            true, true, true, true, true, true, true, true },
/*5*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            true, true, true, true, true, true, true, true },
/*6*/{ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
            true, true, true, true, true, true },
/*7*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            true, true, true, true, true, true, true, true },
/*8*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*9*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*10*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*11*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*12*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*13*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*14*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*15*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false, false },
/*16*/{ false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false,
            true, true, true, true, true, false, false, false, false },
/*17*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, true,
            true, true, true, true, false, false, false, false },
/*18*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, true,
            true, true, true, true, false, false, false, false },
/*19*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, true,
            true, true, true, true, false, false, false, false },
/*20*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, true,
            true, true, true, true, false, false, false, false },
/*21*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false },
/*22*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false },
/*23*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false },
/*24*/{ true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false,
            false, false, false, false, false, false, false, false }, };
}